# Generated by Django 5.2.4 on 2025-08-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('disc', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
