# Generated by Django 5.2.4 on 2025-08-16 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='disc',
            new_name='discription',
        ),
    ]
