# Generated by Django 5.2.4 on 2025-08-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('subject', models.CharField(default='', max_length=100)),
                ('message', models.CharField(max_length=10000)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='discription',
            field=models.CharField(max_length=10000),
        ),
    ]
